export const queryKeys = {
  feed: (params?: object) => params ? ['feed', params] as const : ['feed'] as const,
  post: (id: string) => ['post', id] as const,
  profile: (username: string) => ['profile', username] as const,
  categories: () => ['categories'] as const,
  notifications: () => ['notifications'] as const,
  conversations: () => ['conversations'] as const,
  messages: (conversationId: string) => ['messages', conversationId] as const,
  communityMessages: () => ['community-messages'] as const,
  search: (q: string, tab: string) => ['search', q, tab] as const,
  appLayout: () => ['app-layout'] as const,
  adminDashboard: (params?: object) => params ? ['admin-dashboard', params] as const : ['admin-dashboard'] as const,
  adminCategories: () => ['admin-categories'] as const,
  adminReports: (params?: object) => params ? ['admin-reports', params] as const : ['admin-reports'] as const,
}
